from SeqModules.Aligner import Aligner

if __name__ == '__main__':
    lac1 = "GCCTGCGTTAGCTTGAGCCTACCAAAGAACGGTCATACTTACACCCAGTCGTTATAAAAACGATTCGATC" \
           "CTCGTCATAGTCTCGTCCCCTTTGGAGGGGTTCATTGGGCGAATGGATAATTAAGCTATGGTATCCTATC" \
           "AGCTGTGATAACTTGTTATCAAAAGTCAGGAAAACTGACGGGCCCCAAATGCCGTCGGCCATGGAATTGG" \
           "AATAATGGGAATGCCACCAAAACGTGCCTGATTGATGGCTTACGGTGAATTGGTAGGTAAATGAGCTTCC" \
           "AGGCGGAATAGGACACTATGCAGTTTATAAGTTGACCGATTCCTGTGGTTCCTAAGGATTCTTACCTGTG" \
           "TTATACCAGGGACACCGTCCATGAAAGCCGTGCCAAGCTGCCGCAAACCATGCCAGTCTGGATTAGAGTT" \
           "AGTACATTAAAAAGTACGTTTTCGATATGAGCAGGATATCAGCTGATACTTACGGATACTTGTCC"
    lac2 = "GTACATGTCAACAATCATTTGGAGGAAGGACAAAGTATCCGTAAGTATCAGCTGATATCCTGCTCATATC" \
           "GAAAACGTACTTTTTAATGTACTAACTCTAATCCAGACTGGCATGGTTTGCGGCAGCTTGGCACGGCTTT" \
           "CATGGACGGTGTCCCTGGTATAACACAGGTAAGAATCCTTAGGAACCACAGGAATCGGTCAACTTATAAA" \
           "CTGCATAGTGTCCTATTCCGCCTGGAAGCTCATTTACCTACCAATTCACCGTAAGCCATCAATCAGGCAC" \
           "GTTTTGGTGGCATTCCCATTATTCCAATTCCATGGCCGACGGCATTTGGGGCCCGTCAGTTTTCCTGACT" \
           "TTTGATAACAAGTTATCACAGCTGATAGGATACCATAGCTTAATTATCCATTCGCCCAATGAACCCCTCC" \
           "AAAGGGGACGAGACTATGACGAGGATCGAATCGTTTTTATAACTGACTGGGTGTAAGTATGACCGTTCTT" \
           "TGGTGAGGCTCAAGCTAAACATTGGTGATGGCAGGCATGACAACTCAGAAGTCGTTATTGCAGCTC"
    seq1 = "actcgattgcct"
    seq2 = "acttccgaatttggct"

    seq3 = "ACTCGAATCCT"
    seq4 = "GCCGAATTTTGCT"

    align = Aligner(seq3, seq4)
    answer = align.smith_waterman()
    answer.show_alignment()
    answer.save_traceback("test.csv")
    answer.save_alignment("alignment.txt")
